### ISSUE TITLE
Root detection issue with Magisk on Pixel

### ISSUE THREAD

**Issue by jamorford** [evait-security/android-wifi-key-view#1]
Root check not working. The app closes right away with "I need root" despite me granting it. I can see my passwords in the recents screenshot, so it works, but the app doesn't think it is working. Google Pixel with Android 7.1.2 with Magisk 14.2 root. Previously working on same device.

**Comment by Mys7ic** [comment]
Thank you for reporting this issue and sorry for the late answer. While i work on the Oreo support i got a similar situation so i could reproduce it. It seems that not Magisk made the problem. I hope i could solve the problem in the new release. I would be grateful if you can confirm this.

[Wifi Key View v1.5](https://github.com/evait-security/android-wifi-key-view/releases/tag/v1.5)

**Comment by jamorford** [comment]
v1.5 confirmed working on Google Pixel 8.1.0 with Magisk v15.3. Thanks!
