### ISSUE TITLE
Android 11 moved wifi passwords to new location

### ISSUE THREAD

**Issue by anonymous-user** [evait-security/android-wifi-key-view#11]
In Android 11 the wifi passwords are now stored in:

/data/misc/apexdata/com.android.wifi/WifiConfigStore.xml

Would be nice if the app could be updated to check this location.

**Comment by FLX-0x00** [comment]
The whole "functionality" of this app is implemented since android 10 per default in the network manager without the usage of root. 

Example source: https://gadgetstouse.com/blog/2020/09/24/know-wifi-password-on-android/
