### ISSUE TITLE
Does not detect wifi passwords on Pixel 2 running 8.1

### ISSUE THREAD

**Issue by anonymous-user** [evait-security/android-wifi-key-view#2]
On my Pixel 2 I recently noticed that wifi networks are now saved to /data/misc/wifi/WifiConfigStore.xml. I was wondering if the app could be updated to support it? I use Magisk for root and I've granted root permission but it does not read any of my wifi passwords.

**Comment by Mys7ic** [comment]
Thanks for the hint! 
Here ist the Oreo update: [Wifi Key View v1.5](https://github.com/evait-security/android-wifi-key-view/releases/tag/v1.5) (only available on GitHub at the moment ;) )

**Comment by anonymous-user** [comment]
Thanks!
