### ISSUE TITLE
Add an adaptive icon

### ISSUE THREAD

**Issue by rodrigoswz** [evait-security/android-wifi-key-view#4]
Please, can you add an adaptive icon for WiFi Key View? 

It's a simple thing just for the app icon follow the default shape of the device system.

More info: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive

**Comment by FLX-0x00** [comment]
Right, but we do not want to spend any more time on further development. We have some other project that needs our focus. PR welcome, but the app is dead actually as google build in the feature of view / sharing wifi password in newer versions of android.
